const {
  registerController,
  keepLoginController,
  emailVerificationController,
  verificationController,
  loginController,
  forgotPasswordController,
  tokenPasswordController,
  changePassword,
  profilePictureController,
  resetPasswordController,
} = require("./authController");
const {
  loginAdminController,
  filterProductsController,
  getOrdersController,
  validPrescriptionController,
  getProductsController,
  newProductController,
  getProductDetailsController,
  editProductController,
  deleteProductController,
  getReportController,
  addStockController,
  getNameController,
  getProductStockController,
} = require("./adminController");
const {
  fetchProductsController,
  fetchProductDetailsController,
  fetchPromoProductsController,
  filterProductController,
} = require("./productController");

const {
  updateProfile,
  getUserDetails,
  addNewAddressController,
  changePrimaryAddressController,
  editAddressController,
  getPrimaryAddressController,
  getAllAddressesController,
} = require("./profileControllers");
const {
  fetchProvincesController,
  fetchCitiesController,
  fetchCostController,
} = require("./rajaOngkirController");
const {
  uploadReceipeController,
  rejectOrderController,
  confirmOrderController,
  getUserOrdersController,
  addToCartController,
  getCartController,
  editQuantityonCartController,
  deleteProductCartController,
  getCartPrescriptionController,
  uploadPaymentProofController,
  paymentMethodController,
  getOrderDetailsController,
  orderReceivedController,
} = require("./transactionController");

module.exports = {
  newProductController,
  registerController,
  keepLoginController,
  emailVerificationController,
  verificationController,
  loginAdminController,
  loginController,
  forgotPasswordController,
  tokenPasswordController,
  changePassword,
  fetchProductsController,
  fetchProductDetailsController,
  profilePictureController,
  filterProductController,
  resetPasswordController,
  fetchPromoProductsController,
  addToCartController,
  getCartController,
  editQuantityonCartController,
  deleteProductCartController,
  updateProfile,
  getUserDetails,
  uploadReceipeController,
  fetchProvincesController,
  fetchCitiesController,
  addNewAddressController,
  changePrimaryAddressController,
  rejectOrderController,
  confirmOrderController,
  fetchCostController,
  filterProductsController,
  getOrdersController,
  validPrescriptionController,
  getProductsController,
  deleteProductController,
  getProductDetailsController,
  editProductController,
  getReportController,
  getNameController,
  addStockController,
  getProductStockController,
  getUserOrdersController,
  editAddressController,
  getAllAddressesController,
  getPrimaryAddressController,
  getCartPrescriptionController,
  uploadPaymentProofController,
  paymentMethodController,
  getOrderDetailsController,
  orderReceivedController,
};
